{{- if .Values.autoscaling.enabled }}
{{- $environment := .Values.environment | default "production" }}
{{- $envConfig := index .Values.environments $environment }}
{{- $mergedAutoscaling := .Values.autoscaling }}
{{- if and $envConfig $envConfig.autoscaling }}
{{- $mergedAutoscaling = mustMergeOverwrite $mergedAutoscaling $envConfig.autoscaling }}
{{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ai-news-curator.fullname" . }}
  namespace: {{ include "ai-news-curator.namespace" . }}
  labels:
    {{- include "ai-news-curator.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ai-news-curator.fullname" . }}
  minReplicas: {{ $mergedAutoscaling.minReplicas }}
  maxReplicas: {{ $mergedAutoscaling.maxReplicas }}
  metrics:
    {{- if $mergedAutoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $mergedAutoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $mergedAutoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $mergedAutoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
{{- end }}