{{- if .Values.persistence.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai-news-curator.fullname" . }}-logs
  namespace: {{ include "ai-news-curator.namespace" . }}
  labels:
    {{- include "ai-news-curator.labels" . | nindent 4 }}
  {{- with .Values.persistence.logs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  {{- include "ai-news-curator.storageClass" . | nindent 2 }}
{{- end }}