{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-news-curator.fullname" . }}-secrets
  namespace: {{ include "ai-news-curator.namespace" . }}
  labels:
    {{- include "ai-news-curator.labels" . | nindent 4 }}
  {{- $secretAnnotations := include "ai-news-curator.secretAnnotations" . }}
  {{- if $secretAnnotations }}
  annotations:
    {{- $secretAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- if not .Values.secrets.data.JWT_SECRET }}
  JWT_SECRET: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if not .Values.secrets.data.ENCRYPTION_KEY }}
  ENCRYPTION_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if not .Values.secrets.data.API_KEY_SALT }}
  API_KEY_SALT: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  # External API Keys (to be provided during deployment)
  # OPENAI_API_KEY: ""
  # PINECONE_API_KEY: ""
  # BROWSERBASE_API_KEY: ""
  # BROWSERBASE_PROJECT_ID: ""
  # OAUTH_GOOGLE_CLIENT_SECRET: ""
  # OAUTH_GITHUB_CLIENT_SECRET: ""
{{- end }}