version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "ai-news-curator-team"
    reviewers:
      - "ai-news-curator-team"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "prettier"
          - "jest"
          - "ts-*"
          - "nodemon"
          - "supertest"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "express"
          - "ioredis"
          - "winston"
          - "helmet"
          - "cors"
        update-types:
          - "patch"
    ignore:
      # Ignore major version updates for critical dependencies
      # to prevent breaking changes
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ioredis"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"