apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-news-curator
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ai-news-curator
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          value: "development"