apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-news-curator-dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

configMapGenerator:
  - name: ai-news-curator-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - ENABLE_DEBUG_LOGGING=true
      - DB_SSL=false

replicas:
  - name: ai-news-curator
    count: 1
  - name: postgres
    count: 1
  - name: redis
    count: 1

images:
  - name: ai-news-curator
    newTag: dev-latest