apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-news-curator

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: ai-news-curator
  app.kubernetes.io/instance: ai-news-curator
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: ai-news-curator
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ai-news-curator
    newTag: latest