apiVersion: v1
kind: Secret
metadata:
  name: ai-news-curator-secrets
  namespace: ai-news-curator
  labels:
    app: ai-news-curator
type: Opaque
stringData:
  # Database
  DB_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  
  # Redis
  REDIS_PASSWORD: ""
  
  # API Keys - These must be base64 encoded in production
  ANTHROPIC_API_KEY: "your_anthropic_api_key_here"
  PINECONE_API_KEY: "your_pinecone_api_key_here"
  OPENAI_API_KEY: "your_openai_api_key_here"
  
  # Security
  JWT_SECRET: "your_jwt_secret_here"
  
  # External Services
  SOURCE_CONFIG_URL: "https://example.com/sources.json"
  PINECONE_INDEX_NAME: "ai-content-index"
  PINECONE_ENVIRONMENT: "us-east-1-aws"