apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-news-curator-staging

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: ai-news-curator-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info

replicas:
  - name: ai-news-curator
    count: 2

images:
  - name: ai-news-curator
    newTag: staging-latest

commonAnnotations:
  environment: staging